Eticaret.Magaza/Controllers/FaturaController.cs
using Eticaret.Magaza.Services;
using Eticaret.Model;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Magaza.Controllers
{
    [Route("fatura")]
    public class FaturaController : Controller
    {
        ISatisService _satisService;
        ISatisDetayService _satisDetayService;

        public FaturaController(ISatisService satisService, ISatisDetayService satisDetayService)
        {
            _satisService = satisService;
            _satisDetayService = satisDetayService;

        }

        [Route("{faturaNo}")]
        public async Task<ViewResult> Index(string faturaNo)
        {
            Satis satis = await _satisService.GetByFaturaNoAsync(faturaNo);
            List<SatisDetay> satisDetay = await _satisDetayService.GetBySatis(satis.Id);

            ViewBag.Satis = satis;
            ViewBag.SatisDetay = satisDetay;

            return View();
        }
    }
}

Eticaret.Magaza/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Magaza.Controllers
{
    [Route("")]
    public class HomeController : Controller
    {
        [HttpGet, Route("")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

Eticaret.Magaza/Controllers/KategoriController.cs
using Eticaret.Magaza.Services;
using Eticaret.Model;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Magaza.Controllers
{
    [Route("kategori")]
    public class KategoriController : Controller
    {
        private readonly IKategoriService _kategoriService;
        private readonly IUrunService _urunService;

        public KategoriController(IKategoriService kategoriService, IUrunService urunService)
        {
            _kategoriService = kategoriService;
            _urunService = urunService;
        }

        [HttpGet, Route("{url}")]
        public async Task<ViewResult> Index(string url)
        {
            Kategori? kategori = await _kategoriService.GetAsync(url);
            List<Urun> urunler = new();

            if (kategori != null)
                urunler = await _urunService.GetAllByKategori(kategori.Id);

            ViewBag.Kategori = kategori;
            ViewBag.Urunler = urunler;

            return View();
        }
    }
}

Eticaret.Magaza/Controllers/SepetController.cs
using Eticaret.Magaza.Services;
using Eticaret.Model;
using Eticaret.Model.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Magaza.Controllers
{
    [Route("sepet")]
    public class SepetController : Controller
    {
        private readonly ISatisService _satisService;
        private readonly ISatisDetayService _satisDetayService;

        public SepetController(ISatisService satisService, ISatisDetayService satisDetayService)
        {
            _satisService = satisService;
            _satisDetayService = satisDetayService;
        }

        [HttpPost, Route("sepet-onay")]
        public async Task<JsonResult> SepetOnay(List<SepetUrun> urunler)
        {
            Satis satis = new()
            {
                FaturaNo = await _satisService.GetLastFaturaNoAsync(),
                Tarih = DateTime.Now,
            };

            Guid yeniSatisId = await _satisService.CreateAsync(satis);

            List<SatisDetay> satisDetay = urunler.Select(m => new SatisDetay()
            {
                Adet = m.Adet,
                UrunId = m.Id,
                Fiyat = m.Fiyat,
                SatisId = yeniSatisId,
            }).ToList();

            await _satisDetayService.CreateAsync(satisDetay);

            string faturaNo = await _satisService.GetFaturaNoAsync(yeniSatisId);

            return Json(faturaNo);
        }

        [Route("")]
        public ViewResult Index()
        {
            return View();
        }
    }
}

Eticaret.Magaza/Views/Fatura/Index.cshtml
@using Eticaret.Model

@{
    Satis satis = (Satis)ViewBag.Satis;
    List<SatisDetay> satisDetay = (List<SatisDetay>)ViewBag.SatisDetay;
    Layout = null;
}

<html>
<head>
    <title>Fatura</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                BiMilyoncu Perakende Mağazacılık A.Ş.
                <br />
                Kızılsaray Mahalesi, Hor Hor Apt. B Blok
                <br />
                MURATPAŞA / ANTALYA
                <br />
                Tel No: 0 (242) 555 55 55
                <br />
                Ticaret Sicil No: 1234
                <br />
                Mersis No: 1234 5678 9123 4567
                <br />
                Vergi Dairesi: ÜÇKAPILAR
                <br />
                VKN: 1234567890
                <br />
                <br />
                <b>ETTN:</b> @satis.Id
            </div>
            <div class="col-md-2">
                <center>
                    <img src="https://seeklogo.com/images/G/gelir-idaresi-baskanligi-yeni-logo-FCA1A618F0-seeklogo.com.png" style="width: 7rem;" />
                    <br />
                    <b>e-FATURA</b>
                </center>
            </div>
            <div class="col-md-4">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td class="fw-bold">Özelleştirme No:</td>
                            <td>TR1.2.1</td>
                        </tr>
                        <tr>
                            <td class="fw-bold">Fatura Tipi:</td>
                            <td>Satış</td>
                        </tr>
                        <tr>
                            <td class="fw-bold">Fatura No:</td>
                            <td>@satis.FaturaNo</td>
                        </tr>
                        <tr>
                            <td class="fw-bold">Fatura Tarihi:</td>
                            <td>@satis.Tarih.ToString("dd-MM-yyyy")</td>
                        </tr>
                        <tr>
                            <td class="fw-bold">Fatura Saati:</td>
                            <td>@satis.Tarih.ToString("HH:mm:ss")</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Ürün Adı</th>
                            <th class="text-end">Adet</th>
                            <th class="text-end">Tutar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (SatisDetay detay in satisDetay)
                        {
                            <tr>
                                <td>@detay.Urun!.Ad</td>
                                <td class="text-end">@detay.Adet</td>
                                <td class="text-end">@(detay.Adet * detay.Fiyat) ₺</td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="2" class="text-end">@satisDetay.Select(m=> m.Adet).Sum()</td>
                            <td class="text-end">@(satisDetay.Select(m => m.Fiyat * m.Adet).Sum()) ₺</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

Eticaret.Magaza/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Anasayfa";
}

Eticaret.Magaza/Views/Kategori/Index.cshtml
@using Eticaret.Model

@{
    Kategori? kategori = (Kategori?)ViewBag.Kategori;
    List<Urun> urunler = (List<Urun>)ViewBag.Urunler;
}

@if (kategori == null)
{
    <div class="row">
        <div class="col-md-12">
            <center>
                <h1>Kategori Bulunamadı</h1>
            </center>
        </div>
    </div>
}
else
{
    <div class="row mb-3">
        <div class="col-md-12">
            <h1>@kategori.Ad</h1>
        </div>
    </div>

    <div class="row">
        @foreach (Urun urun in urunler)
        {
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        @if (urun.GorselAd != null)
                        {
                            <center>
                                <img style="height: 150px;" src="https://localhost:7274/img/@urun.GorselAd" class="img-fluid" />
                            </center>
                        }
                        else
                        {
                            <center>
                                <img class="img-fluid" style="height: 150px;" src="https://png.pngtree.com/png-vector/20221125/ourmid/pngtree-no-image-available-icon-flatvector-illustration-pic-design-profile-vector-png-image_40966566.jpg" />
                            </center>
                        }
                        <h5>@urun.Ad</h5>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between align-items-center">
                            <span>@urun.Fiyat</span>
                            <button class="btn btn-sm btn-primary" onclick="sepeteEkle('@urun.Id', '@urun.Ad', @urun.Fiyat);">Sepete Ekle</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}

@section Scripts{
    <script>
        var sepet = localStorage.getItem("sepet");
        var sepetButon = document.getElementById("sepetButon");

        if (sepet == null) {
            sepet = [];
            sepetButon.innerText = "0";
        } else {
            sepet = JSON.parse(sepet);
            let toplamAdet = sepet.reduce((acc, m) => acc += m.adet, 0);
            sepetButon.innerText = toplamAdet;
        }

        function sepeteEkle(id, ad, fiyat) {
            let bulunanIndex = sepet.findIndex(m => m.id == id);

            if (bulunanIndex == -1) {
                let yeniUrun = {
                    id: id,
                    ad: ad,
                    fiyat: fiyat,
                    adet: 1
                };

                sepet.push(yeniUrun);
            } else {
                sepet[bulunanIndex].adet += 1;
            }

            let toplamAdet = sepet.reduce((acc, m) => acc += m.adet, 0);
            sepetButon.innerText = toplamAdet;
            localStorage.setItem("sepet", JSON.stringify(sepet));
        }
    </script>
}

Eticaret.Magaza/Views/Sepet/Index.cshtml
<div class="row mt-4">
    <div class="col-md-6" id="urunler">
        <ul class="list-group">
        </ul>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title mb-0">Sepet Özeti</h3>
            </div>
            <div class="card-body">
                <div>Net Tutar: <span id="sepetNetTutar"></span></div>
                <div>Toplam KDV: <span id="sepetToplamKdv"></span></div>
                <div>Kargo Ücreti: <span id="sepetKargoUcreti"></span></div>
                <div>Brüt Tutar: <span id="sepetBrutTutar"></span></div>
            </div>
            <div class="card-footer">
                <button class="btn btn-lg btn-success w-100" onclick="sepetiOnayla()">Sepeti Onayla</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        var sepet = localStorage.getItem("sepet");
        var sepetButon = document.getElementById("sepetButon");

        var sepetNetTutar = document.getElementById("sepetNetTutar");
        var sepetToplamKdv = document.getElementById("sepetToplamKdv");
        var sepetKargoUcreti = document.getElementById("sepetKargoUcreti");
        var sepetBrutTutar = document.getElementById("sepetBrutTutar");

        var satirIskelet = `<li class="list-group-item" id="ID"> <div class="d-flex justify-content-between"> <div id="ID-ad" style="width: 10rem;"></div> <div id="ID-tutar"></div> <div> <button class="btn btn-sm btn-danger" onclick="urunAzalt('ID')">-</button> <span id="ID-adet"></span> <button class="btn btn-sm btn-success" onclick="urunArttir('ID')">+</button> </div> </div> </li>`;

        if (sepet == null) {
            sepet = [];
            sepetButon.innerText = "0";
        } else {
            sepet = JSON.parse(sepet);
            let toplamAdet = sepet.reduce((acc, m) => acc += m.adet, 0);
            sepetButon.innerText = toplamAdet;
        }

        sepet.forEach(m => {
            let urunlerDiv = document.getElementById("urunler");
            let ul = urunlerDiv.childNodes[1];
            let yeniSatir = satirIskelet;

            yeniSatir = yeniSatir.replaceAll("ID", m.id);
            ul.innerHTML += yeniSatir;

            document.getElementById(`${m.id}-tutar`).innerText = m.fiyat * m.adet;
            document.getElementById(`${m.id}-adet`).innerText = m.adet;
            document.getElementById(`${m.id}-ad`).innerText = m.ad;
        });

        toplamHesapla();

        function toplamHesapla() {
            let brutTutar = sepet.reduce((acc, m) => acc += m.fiyat * m.adet, 0);
            let netTutar = brutTutar / 1.1;
            let toplamKdv = brutTutar - netTutar;

            if (brutTutar < 5000 && sepet.length > 0) {
                brutTutar += 100;
                sepetKargoUcreti.innerText = "100 ₺";
            } else {
                sepetKargoUcreti.innerText = "0 ₺";
            }

            sepetNetTutar.innerText = `${netTutar.toFixed(2)} ₺`;
            sepetToplamKdv.innerText = `${toplamKdv.toFixed(2)} ₺`;
            sepetBrutTutar.innerText = `${brutTutar.toFixed(2)} ₺`;
        }

        function urunArttir(id) {
            let bulunanIndex = sepet.findIndex(m => m.id == id);
            sepet[bulunanIndex].adet += 1;
            document.getElementById(`${id}-adet`).innerText = sepet[bulunanIndex].adet;
            document.getElementById(`${id}-tutar`).innerText = sepet[bulunanIndex].fiyat * sepet[bulunanIndex].adet;
            localStorage.setItem("sepet", JSON.stringify(sepet));
            toplamHesapla();
        }

        function urunAzalt(id) {
            let bulunanIndex = sepet.findIndex(m => m.id == id);

            if (sepet[bulunanIndex].adet == 1) {
                sepet = sepet.filter(m => m.id != id);
                document.getElementById(id).remove();
            } else {
                sepet[bulunanIndex].adet -= 1;
                document.getElementById(`${id}-adet`).innerText = sepet[bulunanIndex].adet;
                document.getElementById(`${id}-tutar`).innerText = sepet[bulunanIndex].fiyat * sepet[bulunanIndex].adet;
            }

            localStorage.setItem("sepet", JSON.stringify(sepet));
            toplamHesapla();
        }

        function sepetiOnayla() {
            if (sepet.length == 0) {
                Swal.fire({
                    icon: "warning",
                    title: "Sepetiniz Boş",
                    confirmButtonText: "Kapat",
                })
            } else {
                Swal.fire({
                    title: "Sepeti Onayla",
                    text: "Siparişinizi onaylamak istiyor musunuz?",
                    icon: "question", // error, info, warning, success
                    confirmButtonText: "Onayla",
                    denyButtonText: "Hayır",
                    cancelButtonText: "Kapat",
                    showDenyButton: true,
                    showCancelButton: false,
                    confirmButtonColor: "green",
                    allowOutsideClick: false,
                })
                    .then(function (res) {
                        if (res.isConfirmed) {
                            Swal.fire({
                                icon: "info",
                                title: "Sepetiniz Onaylanıyor...",
                                showConfirmButton: false,
                                allowOutsideClick: false,
                            });

                            setTimeout(() => {
                                $.ajax({
                                    url: "/sepet/sepet-onay",
                                    method: "post",
                                    data: { urunler: sepet },
                                    success: function (res) {
                                        Swal.fire({
                                            icon: "success",
                                            title: "Sepet Onaylandı",
                                            text: "Siparişiniz alındı.",
                                            showConfirmButton: false,
                                            allowOutsideClick: false,
                                        });

                                        localStorage.removeItem("sepet");

                                        setTimeout(() => {
                                            window.location = `/fatura/${res}`;
                                        }, 2000);
                                    },
                                    error: function (err) {
                                        console.log(err);
                                    }
                                });
                            }, 2000);
                        }
                    });
            }
        }
    </script>
}

Eticaret.Magaza/Views/Shared/_Layout.cshtml
@using Eticaret.Magaza.Services
@using Eticaret.Model
@using Eticaret.Model.ViewModels;
@using Newtonsoft.Json;

@inject IKategoriService kategoriService

@{
    Doviz? doviz = new();
    string apiUrl = "https://localhost:7077/Doviz/Get?doviz=usd";

    List<Kategori> kategoriler = await kategoriService.GetAllAsync();

    using HttpClient client = new();
    HttpResponseMessage response = await client.GetAsync(apiUrl);

    if (response.IsSuccessStatusCode)
    {
        string responseBody = await response.Content.ReadAsStringAsync();
        doviz = JsonConvert.DeserializeObject<Doviz>(responseBody);
    }
    else
    {
        doviz = null;
    }
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eticaret.Magaza</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-success navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">BiMilyoncu</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    @foreach (Kategori kategori in kategoriler)
                    {
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Kategori" asp-action="Index" asp-route-url="@kategori.Url">@kategori.Ad</a>
                        </li>
                    }
                </ul>
                <form class="d-flex align-items-center" role="search">
                    <input class="form-control me-2" type="search" placeholder="Ürün ara..." aria-label="Search">
                    <button class="btn btn-outline-light" type="submit">Ara</button>

                    @if (doviz != null)
                    {
                        <div style="margin-left: 15px; width: 200px; color: white;">@doviz.Ad = @doviz.Kur ₺</div>
                    }

                    <a href="/sepet" class="btn btn-danger ms-2" type="button" id="sepetButon">Sepet</a>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>