Eticaret.Panel/Controllers/SatisController.cs
using Eticaret.Model;
using Eticaret.Panel.Managers;
using Microsoft.AspNetCore.Mvc;

namespace Eticaret.Panel.Controllers
{
    [Route("satis")]
    public class SatisController : Controller
    {
        [Route("")]
        public async Task<ViewResult> Index(string faturaNo, DateTime baslangicTarihi, DateTime bitisTarihi, string tutar)
        {
            List<Satis> satislar;

            if (faturaNo == null && baslangicTarihi.Year == 1 && bitisTarihi.Year == 1 && tutar == null)
            {
                satislar = await SatisManager.TumunuGetir();
            }
            else
            {
                satislar = await SatisManager.Filtrele(faturaNo, baslangicTarihi, bitisTarihi, tutar);
            }

            return View(satislar);
        }
    }
}

Eticaret.Panel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eticaret.Panel</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Bi Milyoncu</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Anasayfa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Satis" asp-action="Index">Satışlar</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Kategori
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Kategori" asp-action="Index">Kategorileri Listele</a></li>
                            <li><a class="dropdown-item" asp-controller="Kategori" asp-action="Yeni">Yeni Kategori Ekle</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Ürün
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Urun" asp-action="Index">Ürünleri Listele</a></li>
                            <li><a class="dropdown-item" asp-controller="Urun" asp-action="Yeni">Yeni Ürün Ekle</a></li>
                        </ul>
                    </li>
                </ul>
                <div class="d-flex">
                    <a asp-controller="Oturum" asp-action="CikisYap" class="btn btn-danger">Çıkış Yap</a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>